<?php

function gfi_demo_menu() {
  $items = array();

  $items['gfi'] = array(
    'page callback' => '_gfi_demo_homepage',
    'type' => MENU_NORMAL_ITEM,
    'title' => 'GFI demo module',
    'menu_name' => 'main-menu',
    'access arguments' => array('access content')
  );

  return $items;
}

function _gfi_demo_homepage() {

  $build = array();

  $build['introduction'] = array(
    '#type' => 'markup',
    '#markup' => '<h2>Bienvenue</h2>'
  );

  $build['contenu'] = array(
    '#type' => 'html_tag',
    '#tag' => 'blockquote',
    '#value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus faucibus eget tortor et commodo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas',
    '#attributes' => array('class' => 'mycssclass')
  );

  $build['tableau'] = array(
    '#theme' => 'table',
    '#header' => array(t('Heading 1'), t('Heading 2'), t('Heading 3')),
    '#rows' => array(
      array('value 1-1', 'value 1-2', 'value 1-3'),
      array('value 2-1', 'value 2-2', 'value 2-3'),
      array(
        array('data' => 'value 3-1', 'colspan' => '2', 'class' => array('cell-class-3-1')),
        array('data' => 'value 3-3', 'class' => array('cell-class-3-3')),
      ),
    ),
    '#attributes' => array('class' => array('table')),
    '#empty' =>t('Your table is empty'),
  );

  $build['accordion'] = array(
    '#theme' => 'accordion',
    '#title' => 'Exemple fonction de theme',
    '#items' => array(
      array(
        'title' => 'title #1',
        'body' => 'body #1'
      )
    )
  );

  return $build;
}

function gfi_demo_preprocess_page(&$variables) {
  if(arg(0) == 'gfi') {
    //dpm($variables['page']['content']['system_main']);
  }
}

function gfi_demo_theme() {
  return array(
    'accordion' => array(
      'template' => 'accordion',
      'path' => drupal_get_path('module', 'gfi_demo').'/templates',
      'variables' => array(
        'title' => NULL,
        'items' => NULL,
      ),
    )
  );
}
